---
apiVersion: v1
kind: Config
current-context: {{ envName }}
contexts:
  - name: {{ envName }}
    context:
      cluster: {{ envName }}
      user: {{ envName }}
      namespace: default
clusters:
  - name: {{ envName }}
    cluster:
      server: {{ clusterEndpoint }}
      certificate-authority-data: {{ clusterCa }}
users:
  - name: {{ envName }}
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws-iam-authenticator
        args:
          - token
          - --cluster-id
          - {{ clusterName }}
          - --role
          - {{ deployerRoleArn }}
