# https://github.com/repository-settings/app

# https://github.com/gitfool/.github/blob/main/.github/settings.yml
_extends: .github

repository:
  topics: devops, pulumi, aws, kubernetes, csharp, dotnet

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - build
