---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-full-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k8s-full-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-read-only
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-read-only
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k8s-read-only
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-auth
data:
  mapRoles: |
    - rolearn: {{ nodeRoleArn }}
      username: system:node:{{ '{{' }}EC2PrivateDNSName{{ '}}' }}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: {{ deployerRoleArn }}
      username: deployer
      groups:
        - system:masters
    - rolearn: {{ fullAccessRoleArn }}
      username: k8s-full-access
    - rolearn: {{ readOnlyRoleArn }}
      username: k8s-read-only
