# extends: _global

Dungeon:
  Environment:
    Name: beta
    DisplayName: Beta
    DefaultTags:
      Environment: Beta
    Aws:
      AccountId: 123456789012
      Region: us-west-2
      Ec2:
        KeyName: beta
      Route53:
        Internal:
          Domain: beta.aws
        Internet:
          Domain: beta.aws
      Vpc:
        CidrBlock: 10.2.0.0/16
